version: '3.7'
services:
  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src
      - /usr/src/node_modules
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    command: npm start
